"""Deterministic, offline realized-trade simulation research."""

from spy_research.execution.classification import classify_execution_variants
from spy_research.execution.classification_models import (
    ExecutionClassificationInputError,
    ExecutionControlReference,
    ExecutionGateResults,
    ExecutionVariantClassification,
    ExecutionVariantClassificationReport,
    ExecutionVariantClassificationRow,
    ExecutionWarning,
    Stage14ExecutionHandoff,
    execution_variant_classification_hash,
)
from spy_research.execution.classification_service import (
    ACCEPTED_STAGE13_1_HASH,
    ACCEPTED_STAGE13_2_HASH,
    ExecutionVariantClassificationService,
)

from spy_research.execution.exit_models import (
    ExitBootstrapInterval,
    ExitBootstrapUncertainty,
    ExitComparisonInputError,
    ExitFamily,
    ExitModelComparisonReport,
    ExitModelExitReason,
    ExitModelStatus,
    ExitModelTradePath,
    ExitModelVariant,
    ExitMonthlyStatistics,
    ExitPartitionStatistics,
    ExitSliceStatistics,
    ExitVariantStatistics,
    LeaveOneMonthOutR,
    NormalizedCrossExitEvent,
    ScheduledExit,
    exit_model_comparison_hash,
    exit_variant_identity,
)
from spy_research.execution.exit_service import ExitModelComparisonService
from spy_research.execution.exit_simulator import (
    select_opposite_cross_exit,
    simulate_exit_model_trade,
)
from spy_research.execution.exit_statistics import (
    BOOTSTRAP_RESAMPLES,
    BOOTSTRAP_SEED,
    bootstrap_exit_variant,
    summarize_exit_variant,
    trade_views,
)
from spy_research.execution.exit_variants import exit_model_variants

from spy_research.execution.fixed_risk import (
    STOP_MULTIPLIERS,
    TARGET_MULTIPLES,
    fixed_risk_variants,
    strategy_populations,
)
from spy_research.execution.models import (
    AmbiguityMetadata,
    AtrStopModel,
    DirectionTradeStatistics,
    ExecutableTradeSetup,
    ExecutionInputError,
    FixedRiskSimulationReport,
    FixedRiskTradeStatistics,
    FixedRiskVariant,
    MonthlyTradeStatistics,
    PopulationReconciliation,
    RealizedTradePath,
    RiskTargetModel,
    StrategyPopulation,
    TradeExitReason,
    TradeSimulationStatus,
    fixed_risk_simulation_hash,
)
from spy_research.execution.service import FixedRiskSimulationService
from spy_research.execution.simulator import simulate_fixed_risk_trade
from spy_research.execution.statistics import (
    calculate_fixed_risk_report,
    summarize_trade_variant,
)

__all__ = [
    "ACCEPTED_STAGE13_1_HASH",
    "ACCEPTED_STAGE13_2_HASH",
    "BOOTSTRAP_RESAMPLES",
    "BOOTSTRAP_SEED",
    "STOP_MULTIPLIERS",
    "TARGET_MULTIPLES",
    "AmbiguityMetadata",
    "AtrStopModel",
    "DirectionTradeStatistics",
    "ExecutableTradeSetup",
    "ExitBootstrapInterval",
    "ExitBootstrapUncertainty",
    "ExitComparisonInputError",
    "ExitFamily",
    "ExitModelComparisonReport",
    "ExitModelComparisonService",
    "ExitModelExitReason",
    "ExitModelStatus",
    "ExitModelTradePath",
    "ExitModelVariant",
    "ExitMonthlyStatistics",
    "ExitPartitionStatistics",
    "ExitSliceStatistics",
    "ExitVariantStatistics",
    "ExecutionInputError",
    "ExecutionClassificationInputError",
    "ExecutionControlReference",
    "ExecutionGateResults",
    "ExecutionVariantClassification",
    "ExecutionVariantClassificationReport",
    "ExecutionVariantClassificationRow",
    "ExecutionVariantClassificationService",
    "ExecutionWarning",
    "FixedRiskSimulationReport",
    "FixedRiskSimulationService",
    "FixedRiskTradeStatistics",
    "FixedRiskVariant",
    "MonthlyTradeStatistics",
    "LeaveOneMonthOutR",
    "NormalizedCrossExitEvent",
    "PopulationReconciliation",
    "RealizedTradePath",
    "RiskTargetModel",
    "ScheduledExit",
    "StrategyPopulation",
    "Stage14ExecutionHandoff",
    "TradeExitReason",
    "TradeSimulationStatus",
    "calculate_fixed_risk_report",
    "classify_execution_variants",
    "bootstrap_exit_variant",
    "exit_model_comparison_hash",
    "exit_model_variants",
    "exit_variant_identity",
    "execution_variant_classification_hash",
    "fixed_risk_simulation_hash",
    "fixed_risk_variants",
    "simulate_fixed_risk_trade",
    "select_opposite_cross_exit",
    "simulate_exit_model_trade",
    "strategy_populations",
    "summarize_trade_variant",
    "summarize_exit_variant",
    "trade_views",
]
